version = 0.1
[default]
[default.build]
parallel = true
beta_features = false

[default.global.parameters]
stack_name = "mk-bedrock"
region = "us-west-2"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
stack_name = "mk-bedrock"
s3_prefix = "mk-bedrock"
region = "us-west-2"
image_repositories = [ ]

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true
template_file = "template.yml"
dependency_layer = false

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
