version = 0.1

[default.global.parameters]
stack_name = "hello-test"
region = "us-east-1"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
stack_name = "hello-test"
s3_prefix = "hello-test"
region = "us-east-1"
image_repositories = [ ]

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true
template_file = "c:\\code\\q-test\\lambda-nodejs22.x\\template.yaml"
dependency_layer = false

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
