AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  lambda-nodejs22.x
  Sample SAM Template for lambda-nodejs22.x

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    Auth:
      ApiKeyRequired: true

Resources:
  BedrockAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: bedrock-analysis-function
      CodeUri: bedrock-analysis/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Timeout: 30
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
                - bedrock:Retrieve
                - bedrock:RetrieveAndGenerate
                - bedrock-agent-runtime:RetrieveAndGenerate
                - bedrock-agent:GetKnowledgeBase
              Resource:
                - !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/*
                - !Sub arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:knowledge-base/*
                - !Sub arn:aws:aoss:${AWS::Region}:${AWS::AccountId}:collection/*
      Events:
        BedrockAnalysis:
          Type: Api
          Properties:
            Path: /analyze
            Method: post
      Environment:
        Variables:
          AWS_SDK_JS_SUPPRESS_MAINTENANCE_MODE_MESSAGE: "1"
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
          AWS_SDK_JS_DEBUG: "true"
      Tracing: Active

  KBSync:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: kb-sync-function
      CodeUri: kb-sync/
      Handler: app.lambdaHandler
      Runtime: nodejs22.x
      Timeout: 30
      Architectures:
        - x86_64
      Policies:
        - S3ReadPolicy:
            BucketName: '*'
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:ListDataSources
                - bedrock:StartIngestionJob
                - bedrock:GetKnowledgeBase
              Resource: 
                - !Sub 'arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:knowledge-base/*'
      Events:
        KBSync:
          Type: Api
          Properties:
            Path: /sync
            Method: post
      Environment:
        Variables:
          AWS_SDK_JS_SUPPRESS_MAINTENANCE_MODE_MESSAGE: "1"
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"

  S3unzipFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: s3-unzip-function
      CodeUri: s3unzip/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Timeout: 300 # 5 minute timeout to allow time for zip extraction
      MemorySize: 1024
      Policies:
        - S3ReadPolicy:
            BucketName: '*'
        - S3CrudPolicy:
            BucketName: '*'
      Architectures:
        - x86_64
      Events:
        S3unzip:
          Type: Api
          Properties:
            Path: /s3unzip
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  BedrockAnalysisApi:
    Description: API Gateway endpoint URL for Prod stage for Bedrock Analysis function
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/analyze/
  BedrockAnalysisFunction:
    Description: Bedrock Analysis Lambda Function ARN
    Value: !GetAtt BedrockAnalysisFunction.Arn
  BedrockAnalysisFunctionIamRole:
    Description: Implicit IAM Role created for Bedrock Analysis function
    Value: !GetAtt BedrockAnalysisFunctionRole.Arn
  S3unzipApi:
    Description: API Gateway endpoint URL for Prod stage for S3 Unzip function
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/s3unzip/
  S3unzipFunction:
    Description: S3 Unzip Lambda Function ARN
    Value: !GetAtt S3unzipFunction.Arn
  S3unzipFunctionIamRole:
    Description: Implicit IAM Role created for S3 Unzip function
    Value: !GetAtt S3unzipFunctionRole.Arn